# Reproducible Research: Peer Assessment 1

## Check for necessary packages. Install and load as necessary

```
if (!require("data.table", "plyr", "hmisc")) {
  install.packages(data.table, plyr, Hmisc)
}
```

## Load and preprocess the data

Store the URL for data
```
fileURL <- c("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip")
```

Store filenames and paths as varriables

```
fileName <- "~/GitHub/RepData_PeerAssessment1/activity.csv"
compressedFileName <- "~/GitHub/RepData_PeerAssessment1/repdata_2Fdata_2Factivity.zip"
```

## Load and preprocess data

Check to see if file exists. Download and extract only if it does not

```
if (!file.exists(fileName)) {
  download.file(fileURL, destfile = zipFileName, method = "curl")
  unzip(zipFileName)
  date = Sys.Date()
}
```

Create data frame in varriable 'activity'. data frame contains threee columns: 
  steps: Number of steps taking in a 5-minute interval (missing values are coded as ð™½ð™°)
  date: The date on which the measurement was taken in YYYY-MM-DD format
  interval: Identifier for the 5-minute interval in which measurement was taken

```
activity <- fread(fileName, na.strings = "NA")
activity$date <- as.Date( activity$date, format = '%Y-%m-%d' )
```

Calculate the total number of steps per day and store as ne data frame

```
totalSteps <- ddply(activity, .(date), summarize, totalSteps = sum(steps))
```

Create a histogram of the total number of stepper day

```
png( 'totalStepsHist.png', width = 480, height = 480)
hist(totalSteps$totalSteps, col = 'blue',  xlab = 'Total Steps per Day')
dev.off()
```

Calculate and report the mean and median of the total number of steps taken per day

```
meanSteps <- summary(totalSteps$totalSteps)['Mean']
medianSteps <- summary(totalSteps$totalSteps)['Median']
meanSteps
medianSteps
```

##Average daily activity pattern

```
aveSteps <- ddply(activity, .(interval), summarize, aveSteps = mean(steps, na.rm=TRUE))
head(aveSteps)
```

Plot the data

```
totalStepsPlot <- hist(totalSteps$totalSteps, col = "blue", xlab = "Total Steps")
print(totalStepsPlot)
```

Find the maximum value

```
maxAveSteps <- summary(aveSteps$aveSteps)['Max.']
print(maxAveSteps)
```

Impute missing values

```
df2 <- ddply(activity, 'date', mutate, imputed.steps = impute(value, mean))
```

Delete complressed files from directory

```
unlink(compressedFileName)
```
